version: '3.9'

services:
  db:
    image: postgres:15
    container_name: askme_db
    restart: always
    environment:
      POSTGRES_DB: askme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - private
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./askme-backend
    container_name: askme_backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./askme-backend:/app
    networks:
      - private
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: askme
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432

  frontend:
    build:
      context: ./askme-frontend
    container_name: askme_frontend
    volumes:
      - ./askme-frontend:/app
    networks:
      - private
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  pgdata:

networks:
  private:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/19"
          gateway: "10.0.0.1"